name: Run Every Minute

on:
  schedule:
    - cron: '* * * * *'  # Every 1 minute
  workflow_dispatch:      # Allows manual triggering too

jobs:
  run-every-minute:
    runs-on: ubuntu-latest
    steps:
      - name: Print time
        run: echo "This job runs every minute"
